version: '3.8'

services:
  # Backend service (Node.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/app_backend/src
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - app_network
    command: ['npm', 'run', 'dev']

  # PostgreSQL Database Service
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '4000:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_database_pg
    volumes:
      - ./database/core.sql:/docker-entrypoint-initdb.d/1_core.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2_data.sql
      - ./database/init.sql:/docker-entrypoint-initdb.d/3_init.sql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
